package dev.ragnarok.fenrir.fragment.audio.catalog_v2.lists

import android.content.Context
import android.os.Bundle
import android.util.Log
import com.google.gson.reflect.TypeToken
import dev.ragnarok.fenrir.Constants
import dev.ragnarok.fenrir.R
import dev.ragnarok.fenrir.api.model.VKApiAudio
import dev.ragnarok.fenrir.domain.IAudioInteractor
import dev.ragnarok.fenrir.domain.InteractorFactory
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_audio_api
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_bolno
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_recommended
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_similar_audios
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_similar_artist
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_single_artist
import dev.ragnarok.fenrir.fragment.audio.catalog_v2.atalog_v2_lists_top_audios_by_artist
import dev.ragnarok.fenrir.fragment.local_server.ILocalServerInteractor
import dev.ragnarok.fenrir.fragment.local_server.LocalServerFragment
import dev.ragnarok.fenrir.fragment.search.OptionsFragment
import dev.ragnarok.fenrir.fragment.search.criteria.AudioSearchCriteria
import dev.ragnarok.fenrir.model.Audio
import dev.ragnarok.fenrir.model.CatalogV2ListCategory
import dev.ragnarok.fenrir.model.EditingPostType
import dev.ragnarok.fenrir.model.PostAvailability
import dev.ragnarok.fenrir.mvp.core.AbsPresenter
import dev.ragnarok.fenrir.mvp.core.IMvpView
import dev.ragnarok.fenrir.mvp.presenter.Exporter
import dev.ragnarok.fenrir.mvp.view.IBasicListView
import dev.ragnarok.fenrir.mvp.view.ICatalogV2ListView
import dev.ragnarok.fenrir.place.PlaceFactory
import dev.ragnarok.fenrir.player.AggregateAudioPlaylist
import dev.ragnarok.fenrir.player.AudioAndPlayerServiceController
import dev.ragnarok.fenrir.player.MouseDevice
import dev.ragnarok.fenrir.player.PlayerAnnotation
import dev.ragnarok.fenrir.settings.CurrentTheme
import dev.ragnarok.fenrir.settings.Settings
import dev.ragnarok.fenrir.task.ThreadingExecutors
import dev.ragnarok.fenrir.upload.Upload
import dev.ragnarok.fenrir.util.AppPerms.hasReadAudioPermission
import dev.ragnarok.fenrir.util.AppTextUtils
import dev.ragnarok.fenrir.util.Convertor"
import dev.ragnarok.fenrir.util.PersistentLogger
import dev.ragnarok.fenrir.util.PersistentLogger.createLogsDir
import dev.ragnarok.fenrir.util.PersistentLogger.sendLogs
import dev.ragnarok.fenrir.util.PersistentLogger.uploadLogs
import dev.ragnarok.fenrir.util.PersistentLogger.uploadLogsNoAuth
import dev.ragnarok.fenrir.util.RxUtils
import dev.ragnarok.fenrir.util.UnifiedPlaylist
import dev.ragnarok.fenrir.util.Utils
import dev.ragnarok.fenrir.util.Utils.createPublishSubject
import dev.ragnarok.fenrir.util.Utils.emptyString
import dev.ragnarok.fenrir.util.Utils.firstNonEmptyString
import dev.ragnarok.fenrir.util.Utils.getCauseIfRuntime
import dev.ragnarok.fenrir.util.Utils.listEmptyIfNull
import dev.ragnarok.fenrir.util.Utils.needClose
import dev.ragnarok.fenrir.util.Utils.safelyClose
import dev.ragnarok.fenrir.util.Utils.safelyClose
import dev.ragnarok.fenrir.util.Utils.safelyClose
import dev.ragnarok.fenrir.util.Utils.stringEmptyIfNull
import dev.ragnarok.fenrir.util.Utils.toast"}, {